dev:
  # Nazwa wymuszona
  children:
    #label / Dowlona nazwa grupy
    agent:
      # Nazwa wymuszona
      hosts:
        # label / dowalna nazawa hosta powiniśmu unikakc -
        lab-agent:
          # nazwa zmien wbudowany - zaczysie od ansible_*
          ansible_host: lab-emilmikolajczak-agent.github.jsystems.cloud
          ansible_user: student

prod:
  children:
    #label / Dowlona nazwa grupy
    master:
      # Nazwa wymuszona
      hosts:
        # label / dowalna nazawa hosta powiniśmu unikakc -
        lab-master:
          # nazwa zmien wbudowany - zaczysie od ansible_*
          ansible_host: lab-emil-mikolajczak.github.jsystems.cloud
          ansible_user: student