---


- name: Install Docker
  apt:
    name: docker.io
    state: present
  become: true

- name: debug variables
  debug:
    msg:
      - "dockerhub_username: {{ dockerhub_username | default('emikolajczak') }}"
      - "docker_image_tag: {{ docker_image_tag | default('emikolajczak') }}"
      - "openweather_api_key: {{ openweather_api_key | default('') }}"

# - name: Pull weather app image created by GitHub Action 99-final-action
#   community.docker.docker_image:
#     name: "{{ dockerhub_username | default('emikolajczak') }}/python_pogoda_29_09_2026"
#     tag: "{{ docker_image_tag | default('emikolajczak') }}"
#     source: pull
#   become: true
#   when: dockerhub_username is defined or docker_image_tag is defined or true

- name: Pull weather app image from Docker Hub
  shell:
    cmd: "docker pull {{ dockerhub_username | default('emikolajczak') }}/python_pogoda_29_09_2026:{{ docker_image_tag | default('emikolajczak') }}"

- name: Run weather app container from Docker Hub image
  shell:
    cmd: "docker run -d --name pogoda_api -p 8000:8000 -e OPENWEATHER_API_KEY={{ openweather_api_key | default('') }} {{ dockerhub_username | default('emikolajczak') }}/python_pogoda_29_09_2026:{{ docker_image_tag | default('emikolajczak') }}"
  become: true


# - name: Run weather app container from Docker Hub image
#   community.docker.docker_container:
#     name: pogoda_api
#     image: "{{ dockerhub_username | default('emikolajczak') }}/python_pogoda_29_09_2026:{{ docker_image_tag | default('emikolajczak') }}"
#     state: started
#     restart_policy: always
#     published_ports:
#       - "8000:8000"
#     env:
#       OPENWEATHER_API_KEY: "{{ openweather_api_key | default('') }}"
#   become: true

- name: Configure Nginx reverse proxy on port 80
  become: true
  copy:
    dest: /etc/nginx/sites-available/weather-app.conf
    content: |
      server {
          listen 80 default_server;
          listen [::]:80 default_server;
          server_name _;

          location / {
              proxy_pass http://127.0.0.1:8000;
              proxy_http_version 1.1;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Enable weather app Nginx site
  become: true
  file:
    src: /etc/nginx/sites-available/weather-app.conf
    dest: /etc/nginx/sites-enabled/weather-app.conf
    state: link
  notify: restart nginx

- name: Disable default Nginx site
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx